#!/usr/bin/env python3
"""
memory_to_wiki.py — 从 OpenViking memories 读取提取的知识，回写到 Wiki 页面。

工作流程:
1. 调用 OpenViking API 检索所有 memories（agent + user scope）
2. 过滤掉 wiki 内部操作产生的 noise（dream_cycle / auto_index 相关）
3. 调用 LLM 从 memories 中提取实体、事件、关系
4. 匹配 wiki 已有页面 → append 到 Timeline
5. 新实体 → 创建 draft 页面（status: draft）
6. 更新 graph.json

数据源: OpenViking REST API (替代旧的 state.db)
依赖: GLM-4-flash API, OpenViking endpoint

用法:
  python3 memory_to_wiki.py                  # 处理所有 memories
  python3 memory_to_wiki.py --dry-run        # 仅分析不修改
  python3 memory_to_wiki.py --verbose        # 显示详细输出
"""

import json
import os
import re
import sys
import time
import yaml
from datetime import datetime
from pathlib import Path
from typing import Optional

# Entity Registry integration
sys.path.insert(0, str(Path(__file__).parent))
try:
    import entity_registry as er
    HAS_REGISTRY = True
except ImportError:
    HAS_REGISTRY = False

# ============ Configuration ============
WIKI_ROOT = Path(os.environ.get("WIKI_ROOT", str(Path.home() / "wiki")))
CONCEPTS_DIR = WIKI_ROOT / "concepts"
ENTITIES_DIR = WIKI_ROOT / "entities"
PEOPLE_DIR = WIKI_ROOT / "people"
PROJECTS_DIR = WIKI_ROOT / "projects"
MEETINGS_DIR = WIKI_ROOT / "meetings"
IDEAS_DIR = WIKI_ROOT / "ideas"
GRAPH_FILE = WIKI_ROOT / "graph.json"
ENV_FILE = Path(os.environ.get("ENV_FILE", str(Path.home() / ".hermes" / ".env")))

LLM_BASE_URL = os.environ.get("GLM_BASE_URL", "https://open.bigmodel.cn/api/paas/v4")
LLM_MODEL = os.environ.get("MEMORY_TO_WIKI_MODEL", "glm-4-flash")
LLM_API_KEY: str = os.environ.get("GLM_API_KEY", "")

# OpenViking config
OV_ENDPOINT = os.environ.get("OPENVIKING_ENDPOINT", "http://127.0.0.1:1933")
OV_API_KEY: str = os.environ.get("OPENVIKING_API_KEY", "")
OV_ACCOUNT = os.environ.get("OPENVIKING_ACCOUNT", "root")
OV_USER = os.environ.get("OPENVIKING_USER", "default")

# Noise patterns — memories generated by wiki automation itself, not user knowledge
NOISE_PATTERNS = [
    r"dream.cycle|dream_cycle|Dream Cycle",
    r"auto_index|auto index|Scale Assurance",
    r"wiki.?lint",
    r"memory_to_wiki",
    r"graph\.json",
    r"frontmatter_update",
    r"relation_fix",
    r"patch.*applied",
]

NOISE_RE = re.compile("|".join(NOISE_PATTERNS), re.IGNORECASE)

# ============ Type → Directory Mapping ============

TYPE_DIR_MAP = {
    "person": PEOPLE_DIR,
    "organization": ENTITIES_DIR,
    "project": PROJECTS_DIR,
    "meeting": MEETINGS_DIR,
    "idea": IDEAS_DIR,
    "entity": ENTITIES_DIR,
    "concept": CONCEPTS_DIR,
}


# ============ Environment Loading ============

def load_env():
    """Load API keys from ~/.hermes/.env if not already set."""
    global LLM_API_KEY, OV_API_KEY, OV_ACCOUNT, OV_USER, OV_ENDPOINT
    if not ENV_FILE.exists():
        return
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key == "GLM_API_KEY" and not LLM_API_KEY:
            LLM_API_KEY = val
        elif key == "OPENVIKING_API_KEY" and not OV_API_KEY:
            OV_API_KEY = val
        elif key == "OPENVIKING_ACCOUNT" and OV_ACCOUNT == "root":
            OV_ACCOUNT = val
        elif key == "OPENVIKING_USER" and OV_USER == "default":
            OV_USER = val
        elif key == "OPENVIKING_ENDPOINT":
            OV_ENDPOINT = val


# ============ OpenViking Client ============

def ov_get(path: str, params: dict = None) -> dict:
    """GET request to OpenViking API."""
    import urllib.request
    import urllib.parse

    url = f"{OV_ENDPOINT}{path}"
    if params:
        url += "?" + urllib.parse.urlencode(params)

    headers = {
        "Authorization": f"Bearer {OV_API_KEY}",
        "X-OpenViking-Account": OV_ACCOUNT,
        "X-OpenViking-User": OV_USER,
    }
    req = urllib.request.Request(url, headers=headers, method="GET")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except Exception as e:
        print(f"⚠ OpenViking API error: {e}")
        return {}


def ov_read(uri: str) -> str:
    """Read full content of a viking:// URI."""
    result = ov_get("/api/v1/content/read", {"uri": uri, "level": "full"})
    if result.get("status") == "ok":
        return result.get("result", "")
    return ""


def ov_post(path: str, payload: dict) -> dict:
    """POST request to OpenViking API."""
    import urllib.request
    url = f"{OV_ENDPOINT}{path}"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {OV_API_KEY}",
        "X-OpenViking-Account": OV_ACCOUNT,
        "X-OpenViking-User": OV_USER,
    }
    data = json.dumps(payload).encode()
    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except Exception as e:
        print(f"⚠ OpenViking POST error: {e}")
        return {}


def fetch_all_memories() -> list[dict]:
    """Fetch all memories from OpenViking via search API."""
    print("📡 Fetching memories from OpenViking...")
    
    all_memories = []
    for scope in ["viking://agent/", "viking://user/"]:
        result = ov_post("/api/v1/search/search", {
            "query": "*",
            "limit": 50,
            "scope": scope,
        })
        memories = result.get("result", result).get("memories", [])
        all_memories.extend(memories)
    
    # Filter to only actual memory files (not .abstract.md or .overview.md)
    memory_files = [
        m for m in all_memories
        if m.get("context_type") == "memory"
        and "/mem_" in m.get("uri", "")
        and not m["uri"].endswith(".abstract.md")
        and not m["uri"].endswith(".overview.md")
    ]
    
    # Deduplicate by URI
    seen = set()
    unique = []
    for m in memory_files:
        uri = m["uri"]
        if uri not in seen:
            seen.add(uri)
            unique.append(m)
    
    # Filter noise (memories about wiki automation itself)
    filtered = []
    for m in unique:
        abstract = m.get("abstract", "")
        if NOISE_RE.search(abstract):
            continue
        filtered.append(m)
    
    print(f"   Found {len(all_memories)} total, {len(memory_files)} memory files, "
          f"{len(filtered)} after noise filter")
    return filtered


def read_memory_contents(memories: list[dict]) -> list[dict]:
    """Read full content for each memory."""
    print(f"📖 Reading memory contents...")
    enriched = []
    for m in memories:
        uri = m.get("uri", "")
        content = ov_read(uri)
        if content:
            enriched.append({
                "uri": uri,
                "abstract": m.get("abstract", ""),
                "content": content,
                "score": m.get("score", 0),
                # Extract category and type from URI path
                "category": _extract_category(uri),
            })
    print(f"   Read {len(enriched)} memories with content")
    return enriched


def _extract_category(uri: str) -> str:
    """Extract memory category from URI path."""
    # viking://agent/.../memories/{category}/mem_xxx.md
    # viking://user/.../memories/{category}/mem_xxx.md
    match = re.search(r"/memories/([^/]+)/mem_", uri)
    if match:
        return match.group(1)
    return "unknown"


# ============ Wiki Page Management ============

def load_existing_pages() -> dict[str, dict]:
    """Load all wiki pages indexed by slug."""
    pages = {}
    for subdir in [CONCEPTS_DIR, ENTITIES_DIR, PEOPLE_DIR, PROJECTS_DIR, MEETINGS_DIR, IDEAS_DIR]:
        if not subdir.exists():
            continue
        for md_file in subdir.glob("*.md"):
            try:
                content = md_file.read_text(encoding="utf-8")
                fm_match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
                title = md_file.stem
                if fm_match:
                    for line in fm_match.group(1).split("\n"):
                        if line.startswith("title:"):
                            title = line.split(":", 1)[1].strip().strip('"').strip("'")
                            break
                pages[md_file.stem] = {
                    "path": str(md_file),
                    "title": title,
                    "content": content,
                }
            except Exception:
                pass
    return pages


def append_to_timeline(filepath: str, entry: str):
    """Append a new entry to a wiki page's Timeline section."""
    path = Path(filepath)
    content = path.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Find the last --- line (the timeline divider)
    last_separator_idx = None
    for i in range(len(lines) - 1, -1, -1):
        if lines[i].strip() == "---":
            last_separator_idx = i
            break

    if last_separator_idx is None:
        content += f"\n---\n\n## Timeline\n\n{entry}\n"
    else:
        insert_idx = last_separator_idx + 1
        while insert_idx < len(lines) and not lines[insert_idx].strip():
            insert_idx += 1
        if insert_idx < len(lines) and lines[insert_idx].strip() == "## Timeline":
            insert_idx += 1
            while insert_idx < len(lines) and not lines[insert_idx].strip():
                insert_idx += 1
        lines.insert(insert_idx, entry)
        content = "\n".join(lines)

    path.write_text(content, encoding="utf-8")
    print(f"  ✓ Timeline updated: {path.name}")


def update_executive_summary(filepath: str, new_summary: str):
    """Rewrite the Executive Summary section of a wiki page."""
    path = Path(filepath)
    content = path.read_text(encoding="utf-8")
    lines = content.split("\n")

    # Find ## Executive Summary section
    summary_start = None
    summary_end = None
    for i, line in enumerate(lines):
        if line.strip() == "## Executive Summary":
            summary_start = i
        elif summary_start is not None and line.strip().startswith("## ") and line.strip() != "## Executive Summary":
            summary_end = i
            break

    if summary_start is None:
        return

    if summary_end is None:
        # No next section — replace till end or ---
        for i in range(summary_start + 1, len(lines)):
            if lines[i].strip() == "---":
                summary_end = i
                break
        if summary_end is None:
            summary_end = len(lines)

    # Replace lines between summary_start+1 and summary_end
    new_lines = lines[:summary_start + 1] + ["", new_summary, ""] + lines[summary_end:]
    content = "\n".join(new_lines)

    # Update the frontmatter updated date
    today = datetime.now().strftime("%Y-%m-%d")
    content = re.sub(r"^(updated:).*", rf"\1 {today}", content, count=1, flags=re.MULTILINE)

    path.write_text(content, encoding="utf-8")
    print(f"  ✓ Executive Summary updated: {path.name}")


def create_wiki_page(entity: dict, existing_pages: dict) -> Optional[str]:
    """Create a new wiki draft page for an entity."""
    entity_type = entity.get("type", "concept")
    name = entity.get("name", "unnamed")
    description = entity.get("description", "")

    # SEC-1: Sanitize inputs to prevent YAML injection
    name = name.replace("\n", " ").replace("\r", " ").strip()
    entity_type = entity_type.replace("\n", " ").replace("\r", " ").strip()
    description = description.replace("\n", " ").replace("\r", " ").strip()

    # Generate slug
    slug = re.sub(r"[^\w\u4e00-\u9fff-]", "-", name.lower())
    slug = re.sub(r"-+", "-", slug).strip("-")

    # SEC-2: Empty slug guard
    if not slug:
        print("  ⚠ Cannot create page: empty slug")
        return None

    # Determine directory using module-level TYPE_DIR_MAP
    dir_path = TYPE_DIR_MAP.get(entity_type, CONCEPTS_DIR)

    filepath = dir_path / f"{slug}.md"
    if filepath.exists():
        print(f"  ⚠ Page already exists: {filepath.name}")
        return slug

    today = datetime.now().strftime("%Y-%m-%d")
    # SEC-1: Build frontmatter safely with yaml.dump (prevents YAML injection)
    fm_dict = {
        "title": name,
        "created": today,
        "updated": today,
        "type": entity_type,
        "tags": [],
        "sources": ["openviking-memory"],
        "status": "draft",
    }
    fm_yaml = yaml.dump(fm_dict, default_flow_style=None, allow_unicode=True, sort_keys=False).rstrip("\n")
    content = f"""---
{fm_yaml}---

# {name}

## Executive Summary

{description}

## Key Facts

_待补充_

## Relations

| 关系 | 目标 | 说明 |
|------|------|------|

---

## Timeline

- **{today}** | 从 OpenViking memory 自动创建此页面
  [Source: OpenViking memory, {today}]
"""
    dir_path.mkdir(parents=True, exist_ok=True)
    filepath.write_text(content, encoding="utf-8")
    print(f"  ✚ Created draft: {filepath.name} ({entity_type})")

    # Register in Entity Registry
    if HAS_REGISTRY:
        try:
            er.register(name, entity_type, str(filepath), aliases=[slug])
        except Exception as e:
            print(f"  ⚠ Registry registration failed: {e}")

    return slug


# ============ LLM Entity Extraction ============

def call_llm(prompt: str, system: str = "") -> str:
    """Call GLM API."""
    import urllib.request

    url = f"{LLM_BASE_URL}/chat/completions"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {LLM_API_KEY}",
    }
    payload = {
        "model": LLM_MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.1,
        "max_tokens": 4096,
    }

    req = urllib.request.Request(
        url, data=json.dumps(payload).encode(), headers=headers, method="POST"
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read())
            return result["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"⚠ LLM error: {e}")
        return ""


def extract_entities(memories: list[dict], existing_pages: dict) -> dict:
    """Use LLM to extract entities and events from OpenViking memories."""
    if not memories:
        return {"entities": [], "events": [], "relations": []}

    # Build memory digest for LLM
    memory_texts = []
    for m in memories[:30]:  # Limit to avoid token overflow
        cat = m.get("category", "?")
        content = m.get("content", "")[:300]
        abstract = m.get("abstract", "")
        memory_texts.append(f"[{cat}] {abstract}\n  {content}")

    memory_digest = "\n---\n".join(memory_texts)

    existing_titles = "\n".join(
        f"- {pid}: {p['title']}" for pid, p in existing_pages.items()
    )

    system_prompt = f"""你是一个知识库维护助手。分析以下从 OpenViking 自动提取的 memories，提取有持久价值的实体和事件。

严格按以下 JSON 格式输出（不要包含 markdown 代码块标记）：
{{
  "entities": [
    {{"name": "实体名", "type": "person|concept|project|tool|organization", "description": "一句话描述", "matched_wiki_id": "已有的wiki页面ID或null"}}
  ],
  "events": [
    {{"description": "事件描述", "related_entities": ["实体名"], "date": "YYYY-MM-DD"}}
  ],
  "relations": [
    {{"source": "实体A", "target": "实体B", "type": "uses|related|part-of|created-by", "note": "说明"}}
  ]
}}

已有 wiki 页面：
""" + existing_titles + """

规则：
- 只提取有实质信息的实体（不是泛泛而谈）
- 如果实体匹配已有 wiki 页面，填写 matched_wiki_id
- 事件必须和已有或新实体关联
- 忽略纯技术操作（如"帮我改个配置"），关注有持久价值的知识
- 对话是中文的，实体名也用中文
- 如果某个 memory 没有有价值的信息，跳过它
- entities 列表可以为空——这表示没有新的有价值的实体需要创建"""

    print(f"🧠 Extracting entities from {len(memories)} memories...")
    raw = call_llm(memory_digest, system_prompt)

    cleaned = raw.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```\w*\n?", "", cleaned)
        cleaned = re.sub(r"\n?```$", "", cleaned)
    cleaned = cleaned.strip()

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        print(f"⚠ LLM output parse failed: {raw[:300]}")
        return {"entities": [], "events": [], "relations": []}


# ============ Main Pipeline ============

def main():
    global LLM_API_KEY
    args = set(sys.argv[1:])
    dry_run = "--dry-run" in args
    verbose = "--verbose" in args

    load_env()

    if not LLM_API_KEY:
        print("❌ GLM_API_KEY not set")
        sys.exit(1)
    if not OV_API_KEY:
        print("❌ OPENVIKING_API_KEY not set")
        sys.exit(1)

    print("🔄 Memory → Wiki Pipeline (OpenViking)")
    print(f"   Mode: {'DRY RUN' if dry_run else 'APPLY'}")
    print(f"   OpenViking: {OV_ENDPOINT}")
    print(f"   LLM: {LLM_MODEL}")
    print()

    # 1. Fetch memories from OpenViking
    memories = fetch_all_memories()
    if not memories:
        print("✅ No memories to process")
        return

    # 2. Read full memory contents
    enriched = read_memory_contents(memories)
    if not enriched:
        print("✅ No memory content to process")
        return

    if verbose:
        for m in enriched:
            print(f"   [{m['category']}] {m['abstract'][:80]}")

    # 3. Load existing wiki pages
    existing_pages = load_existing_pages()
    print(f"   Wiki has {len(existing_pages)} existing pages")

    # 4. Extract entities via LLM
    extraction = extract_entities(enriched, existing_pages)
    entities = extraction.get("entities", [])
    events = extraction.get("events", [])
    relations = extraction.get("relations", [])

    print(f"\n   Extracted: {len(entities)} entities, {len(events)} events, {len(relations)} relations")

    if not entities and not events:
        print("✅ No significant entities found in memories")
        return

    if dry_run:
        print("\n🔍 DRY RUN — no changes made")
        for e in entities:
            match = e.get("matched_wiki_id") or "NEW"
            print(f"  [{match}] {e['name']} ({e['type']}): {e.get('description', '')[:80]}")
        for ev in events:
            print(f"  📅 {ev.get('date', '?')}: {ev['description'][:80]}")
        for r in relations:
            print(f"  🔗 {r['source']} → {r['target']} ({r['type']}): {r.get('note', '')[:60]}")
        return

    # 5. Process entities
    today = datetime.now().strftime("%Y-%m-%d")
    created_slugs = set()

    for entity in entities:
        matched_id = entity.get("matched_wiki_id")
        name = entity.get("name", "")
        description = entity.get("description", "")

        # Check Entity Registry for existing entity
        if not matched_id and HAS_REGISTRY:
            reg_match = er.resolve(name)
            if reg_match:
                reg_page = reg_match.get("primary_page", "")
                if reg_page:
                    reg_slug = Path(reg_page).stem
                    if reg_slug in existing_pages:
                        matched_id = reg_slug

        if matched_id and matched_id in existing_pages:
            # Existing page — append to timeline
            entry = f"- **{today}** | {description}\n  [Source: OpenViking memory, {today}]"
            append_to_timeline(existing_pages[matched_id]["path"], entry)
        else:
            # New entity — create draft page
            slug = create_wiki_page(entity, existing_pages)
            if slug:
                created_slugs.add(slug)
                existing_pages[slug] = {
                    "path": str(TYPE_DIR_MAP.get(entity.get("type", ""), CONCEPTS_DIR) / f"{slug}.md"),
                    "title": name,
                    "content": "",
                }

    # 6. Process events — append to related entity pages
    for event in events:
        for entity_name in event.get("related_entities", []):
            matched = None
            for pid, page in existing_pages.items():
                if entity_name.lower() in page["title"].lower() or entity_name.lower() in pid.lower():
                    matched = pid
                    break
            if matched:
                entry = f"- **{event.get('date', today)}** | {event['description']}\n  [Source: OpenViking memory, {today}]"
                append_to_timeline(existing_pages[matched]["path"], entry)

    # 7. Process relations — add to wiki pages' Relations table
    if relations:
        print(f"\n🔗 Processing {len(relations)} relations...")
        for rel in relations:
            source_name = rel.get("source", "")
            target_name = rel.get("target", "")
            rel_type = rel.get("type", "related")
            note = rel.get("note", "")

            # Find source page
            source_page = None
            for pid, page in existing_pages.items():
                if source_name.lower() in page["title"].lower() or source_name.lower() in pid.lower():
                    source_page = pid
                    break
            if not source_page:
                continue

            # Check if relation already exists
            page_content = Path(existing_pages[source_page]["path"]).read_text(encoding="utf-8")
            if f"| {rel_type} | [[{target_name}]]" in page_content or f"| {rel_type} | {target_name}" in page_content:
                if verbose:
                    print(f"  ⏭ Relation exists: {source_name} → {target_name}")
                continue

            # Find the Relations table and add row
            lines = page_content.split("\n")
            in_relations = False
            insert_idx = None
            for i, line in enumerate(lines):
                if line.strip() == "## Relations":
                    in_relations = True
                elif in_relations and line.strip().startswith("## "):
                    insert_idx = i
                    break
                elif in_relations and line.strip().startswith("|") and "---" not in line:
                    insert_idx = i + 1

            if insert_idx:
                # Escape wiki link syntax if target has wiki page
                target_wiki_id = None
                for pid, page in existing_pages.items():
                    if target_name.lower() in page["title"].lower() or target_name.lower() in pid.lower():
                        target_wiki_id = pid
                        break
                target_display = f"[[{target_wiki_id}]]" if target_wiki_id else target_name

                new_row = f"| {rel_type} | {target_display} | {note} |"
                lines.insert(insert_idx, new_row)
                Path(existing_pages[source_page]["path"]).write_text(
                    "\n".join(lines), encoding="utf-8"
                )
                print(f"  ✓ Relation added: {source_name} → {target_name} ({rel_type})")

    # 8. Update graph.json if new pages were created
    if created_slugs:
        print(f"\n🔗 Updating graph.json...")
        import subprocess
        result = subprocess.run(
            ["python3", str(WIKI_ROOT / "scripts" / "auto_index.py"), "--force"],
            capture_output=True, text=True, cwd=str(WIKI_ROOT),
        )
        if result.returncode == 0:
            print(f"   ✓ Graph updated")
        else:
            print(f"   ⚠ Graph update failed: {result.stderr[:200]}")

    # Update Entity Registry from wiki pages
    if HAS_REGISTRY:
        print(f"\n📋 Updating Entity Registry...")
        try:
            result = er.scan_wiki_pages(str(WIKI_ROOT))
            print(f"   Registry: {result.get('registered', 0)} new, "
                  f"{result.get('updated', 0)} updated, "
                  f"{result.get('skipped', 0)} skipped")
        except Exception as e:
            print(f"   ⚠ Registry update failed: {e}")

    print(f"\n✨ Memory → Wiki pipeline complete!")
    print(f"   Memories processed: {len(enriched)}")
    print(f"   Entities processed: {len(entities)}")
    print(f"   Events processed: {len(events)}")
    print(f"   New pages created: {len(created_slugs)}")


if __name__ == "__main__":
    main()
